---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bortmpcz/public_html/
    - /bin/cp -R pages assets includes vendor *.php *.css *.js .htaccess $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH || true
    - /bin/cp -R database $DEPLOYPATH || true
    - /bin/cp -R uploads $DEPLOYPATH || true
    - /bin/cp favicon.ico $DEPLOYPATH || true
    - /bin/cp robots.txt $DEPLOYPATH || true
    - /bin/rm -rf $DEPLOYPATH/.git $DEPLOYPATH/.env $DEPLOYPATH/.gitignore $DEPLOYPATH/.cpanel.yml || true 